variables:
  DOCKER_IMAGE_NAME: mialkin/dotnet-sdk-with-tools

stages:
  - build
  - publish

build:
  stage: build
  interruptible: true
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build --tag ${DOCKER_IMAGE_NAME}:latest .

publish:
  stage: publish
  interruptible: true
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build --tag ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker login --username ${DOCKER_REGISTRY_USERNAME} --password ${DOCKER_REGISTRY_PASSWORD}
    - docker push ${DOCKER_IMAGE_NAME}:${CI_COMMIT_TAG}
    - docker logout
  rules:
    - if: $CI_COMMIT_TAG =~ /^\d+.\d+.\d+$/