variables:
  DOCKER_IMAGE_NAME: mialkin/dotnet-sdk-9-gitlab-ci

stages:
  - build
  - publish

build:
  stage: build
  interruptible: true
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build --tag ${DOCKER_IMAGE_NAME} .

publish:
  stage: publish
  interruptible: true
  image: docker:stable
  when: manual
  services:
    - docker:dind
  script:
    - docker build --tag ${DOCKER_IMAGE_NAME} .
    - docker login --username ${DOCKER_REGISTRY_USERNAME} --password ${DOCKER_REGISTRY_PASSWORD}
    - docker push ${DOCKER_IMAGE_NAME}
    - docker logout
