variables:
  DOCKER_IMAGE_NAME: mialkin/dotnet8-sdk-with-tools

stages:
  - build
  - publish

build:
  stage: build
  interruptible: true
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build .
